import{a as g,A as b,i as L,S as M,N as S}from"./assets/vendor-09312bac.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const v of r.addedNodes)v.tagName==="LINK"&&v.rel==="modulepreload"&&n(v)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();async function k(e,t){const s={email:e,comment:t};try{return(await g.post("https://portfolio-js.b.goit.study/api/requests",s)).data}catch(n){console.error(n)}}async function O(){try{return(await g.get("https://portfolio-js.b.goit.study/api/reviews")).data}catch(e){return e}}document.addEventListener("DOMContentLoaded",function(){new b(" .accordion-about-container"),new b(" .accordion-faq-container")});const w=document.body,f={formFooter:document.querySelector(".js_form_footer"),closeModalBtn:document.querySelector("[data-modal-close]"),modal:document.querySelector("[data-modal]"),elementModal:document.querySelector(".modal")};f.formFooter.addEventListener("submit",x);async function x(e){e.preventDefault();const t=e.target.elements.email.value.trim(),s=e.target.elements.message.value.trim();if(t.length===0||s.length===0){console.log("input filds"),L.info({position:"topRight",message:"INPUT EMAIL E MESSAGE"});return}else{const n=await k(t,s);console.log(n),C(n),w.style.overflow="hidden",w.style.zIndex=52,q()}}function q(){const e=document.querySelector("[data-modal]"),t=document.querySelector("[data-modal-close]");f.formFooter.reset(),e.classList.remove("is-hidden"),e.addEventListener("click",n=>{n.target===n.currentTarget&&s()}),t.addEventListener("click",()=>s());function s(){e.classList.add("is-hidden")}}const N="./img/icons.svg#icon-close";function C(e){const{title:t,message:s}=e,n=`<button type="button" class="modal-close-btn" data-modal-close>
        <svg class="modal-icon-close">
          <use href="${N}"></use>
        </svg>
      </button>
      <h2 class="modal-title">${t}</h2>
      <p class="modal-text">${s}</p>`;f.elementModal.innerHTML=n}const I=document.getElementById("mobile-menu-close"),j=document.getElementById("mobile-menu-open"),l=document.getElementById("main-modal-menu-open"),d=document.getElementById("mobile-menu-id"),R=document.getElementsByClassName("mobile-menu-nav-list-item"),P=document.getElementById("main-modal-menu-id"),E=document.getElementsByClassName("main-modal-list-item"),a=document.getElementsByTagName("body"),p=document.querySelector(".main-modal-menu"),T=document.getElementsByClassName("order-btn-text");for(let e of R)e.addEventListener("click",()=>{d.classList.remove("is-open"),a[0].classList.remove("no-scroll")});for(let e of E)e.addEventListener("click",()=>{p.classList.remove("is-open"),a[0].classList.remove("no-scroll")});for(let e of E)e.addEventListener("click",()=>{P.classList.remove("is-open"),a[0].classList.remove("no-scroll")});for(let e of T)e.addEventListener("click",()=>{d.classList.remove("is-open"),a[0].classList.remove("no-scroll")});j.addEventListener("click",()=>{d.classList.add("is-open"),a[0].classList.add("no-scroll")});I.addEventListener("click",()=>{d.classList.remove("is-open"),a[0].classList.remove("no-scroll")});l.addEventListener("click",y);function y(){l.addEventListener("click",h),$(),l.removeEventListener("click",y)}function $(){p.classList.add("is-open2")}function h(){p.classList.remove("is-open2"),l.addEventListener("click",y)}document.addEventListener("click",e=>{!p.contains(e.target)&&!l.contains(e.target)&&!d.contains(e.target)&&h()});document.querySelector(".projects-section > .swiper");const i=document.querySelector(".projects-next-btn"),c=document.querySelector(".projects-prev-btn");new Swiper(".mySwiper",{navigation:{nextEl:".projects-next-btn",prevEl:".projects-prev-btn"}});const A=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(i.classList.contains("swiper-button-disabled")?(i.style.opacity="0.5",i.style.cursor="not-allowed"):(i.style.opacity="1",i.style.cursor="pointer"))})});A.observe(i,{attributes:!0});const F=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(c.classList.contains("swiper-button-disabled")?(c.style.opacity="0.5",c.style.cursor="not-allowed"):(c.style.opacity="1",c.style.cursor="pointer"))})});F.observe(c,{attributes:!0});const B=document.querySelector(".reviews-list"),V=document.querySelector(".reviews-swiper"),u=document.querySelector(".reviews-next-btn"),m=document.querySelector(".reviews-prev-btn");function z({avatar_url:e,author:t,review:s}){return`<li class="reviews-item swiper-slide">
              <img class="reviews-item-img" src="${e}" alt="Ihor Trachuk" width="48" height="48" />
              <h3 class="reviews-item-title">${t}</h3>
              <p class="reviews-item-text">
                ${s}
              </p>
          </li>`}function D(e){return e.map(z).join("")}function H(){const e=document.createElement("li"),t=document.createElement("span");e.classList.add("reviews-item-error"),t.textContent="Not found",t.classList.add("reviews-text-error"),e.appendChild(t),B.appendChild(e)}document.addEventListener("DOMContentLoaded",_);async function _(){try{const e=await O(),t=D(e);B.insertAdjacentHTML("beforeend",t)}catch(e){console.error("Error :",e),H(),L.info({close:!1,position:"topRight",message:"Error!"})}}new M(V,{modules:[S],slidesPerView:1,spaceBetween:16,keyboard:{enabled:!0,onlyInViewport:!1},breakpoints:{768:{slidesPerView:2,spaceBetween:18},1440:{slidesPerView:4,spaceBetween:16}},direction:"horizontal",navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"}});const G=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(u.classList.contains("swiper-button-disabled")?u.style.opacity="0.5":u.style.opacity="1")})});G.observe(u,{attributes:!0});const K=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(m.classList.contains("swiper-button-disabled")?m.style.opacity="0.5":m.style.opacity="1")})});K.observe(m,{attributes:!0});
//# sourceMappingURL=commonHelpers.js.map
