import{a as E,A as L,i as h,S as M,N as x}from"./assets/vendor-09312bac.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const i of s)if(i.type==="childList")for(const y of i.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&o(y)}).observe(document,{childList:!0,subtree:!0});function n(s){const i={};return s.integrity&&(i.integrity=s.integrity),s.referrerPolicy&&(i.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?i.credentials="include":s.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function o(s){if(s.ep)return;s.ep=!0;const i=n(s);fetch(s.href,i)}})();async function O(e,t){const n={email:e,comment:t};try{return(await E.post("https://portfolio-js.b.goit.study/api/requests",n)).data}catch(o){console.error(o)}}async function q(){try{return(await E.get("https://portfolio-js.b.goit.study/api/reviews")).data}catch(e){return e}}document.addEventListener("DOMContentLoaded",function(){new L(" .accordion-about-container"),new L(" .accordion-faq-container")});const f=document.body,w={formFooter:document.querySelector(".js_form_footer"),elementModal:document.querySelector(".modal")};w.formFooter.addEventListener("submit",N);async function N(e){e.preventDefault();const t=e.target.elements.email.value.trim();let n=e.target.elements.message.value.trim();if(t.length===0||n.length===0){console.log("input filds"),h.info({position:"topRight",message:"INPUT EMAIL E MESSAGE"});return}else{const o=await O(t,n);P(o),f.style.overflow="hidden",f.style.zIndex=52,C()}}function C(){const e=document.querySelector("[data-modal]"),t=document.querySelector("[data-modal-close]");w.formFooter.reset(),e.classList.remove("is-hidden"),e.addEventListener("click",s=>{s.target===s.currentTarget&&o()}),t.addEventListener("click",()=>o()),document.addEventListener("keydown",n);function n(s){s.key==="Escape"&&(o(),document.removeEventListener("keydown",n))}function o(){e.classList.add("is-hidden"),f.style.overflow="visible",f.style.zIndex=0}}const I="./img/icons.svg#icon-close";function P(e){const{title:t,message:n}=e,o=`<button type="button" class="modal-close-btn" data-modal-close>
        <svg class="modal-icon-close">
          <use href=${I}></use>
        </svg>
      </button>
      <h2 class="modal-title">${t}</h2>
      <p class="modal-text">${n}</p>`;w.elementModal.innerHTML=o}const j=document.getElementById("mobile-menu-close"),R=document.getElementById("mobile-menu-open"),l=document.getElementById("main-modal-menu-open"),m=document.getElementById("mobile-menu-id"),T=document.getElementsByClassName("mobile-menu-nav-list-item"),$=document.getElementById("main-modal-menu-id"),k=document.getElementsByClassName("main-modal-list-item"),a=document.getElementsByTagName("body"),b=document.querySelector(".main-modal-menu"),V=document.getElementsByClassName("order-btn-text");for(let e of T)e.addEventListener("click",()=>{m.classList.remove("is-open"),a[0].classList.remove("no-scroll")});for(let e of k)e.addEventListener("click",()=>{b.classList.remove("is-open"),a[0].classList.remove("no-scroll")});for(let e of k)e.addEventListener("click",()=>{$.classList.remove("is-open"),a[0].classList.remove("no-scroll")});for(let e of V)e.addEventListener("click",()=>{m.classList.remove("is-open"),a[0].classList.remove("no-scroll")});R.addEventListener("click",()=>{m.classList.add("is-open"),a[0].classList.add("no-scroll")});j.addEventListener("click",()=>{m.classList.remove("is-open"),a[0].classList.remove("no-scroll")});l.addEventListener("click",g);function g(){l.addEventListener("click",B),A(),l.removeEventListener("click",g)}function A(){b.classList.add("is-open2")}function B(){b.classList.remove("is-open2"),l.addEventListener("click",g)}document.addEventListener("click",e=>{!b.contains(e.target)&&!l.contains(e.target)&&!m.contains(e.target)&&B()});document.querySelector(".projects-section > .swiper");const r=document.querySelector(".projects-next-btn"),c=document.querySelector(".projects-prev-btn");new Swiper(".mySwiper",{navigation:{nextEl:".projects-next-btn",prevEl:".projects-prev-btn"}});const z=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(r.classList.contains("swiper-button-disabled")?(r.style.opacity="0.5",r.style.cursor="not-allowed"):(r.style.opacity="1",r.style.cursor="pointer"))})});z.observe(r,{attributes:!0});const F=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(c.classList.contains("swiper-button-disabled")?(c.style.opacity="0.5",c.style.cursor="not-allowed"):(c.style.opacity="1",c.style.cursor="pointer"))})});F.observe(c,{attributes:!0});const S=document.querySelector(".reviews-list"),D=document.querySelector(".reviews-swiper"),p=document.querySelector(".reviews-next-btn"),v=document.querySelector(".reviews-prev-btn");function H({avatar_url:e,author:t,review:n}){return`<li class="reviews-item swiper-slide">
              <img class="reviews-item-img" src="${e}" alt="Ihor Trachuk" width="48" height="48" />
              <h3 class="reviews-item-title">${t}</h3>
              <p class="reviews-item-text">
                ${n}
              </p>
          </li>`}function W(e){return e.map(H).join("")}function _(){const e=document.createElement("li"),t=document.createElement("span");e.classList.add("reviews-item-error"),t.textContent="Not found",t.classList.add("reviews-text-error"),e.appendChild(t),S.appendChild(e)}document.addEventListener("DOMContentLoaded",G);async function G(){try{const e=await q(),t=W(e);S.insertAdjacentHTML("beforeend",t)}catch(e){console.error("Error :",e),_(),h.info({close:!1,position:"topRight",message:"Error!"})}}new M(D,{modules:[x],slidesPerView:1,spaceBetween:16,keyboard:{enabled:!0,onlyInViewport:!1},breakpoints:{768:{slidesPerView:2,spaceBetween:18},1440:{slidesPerView:4,spaceBetween:16}},direction:"horizontal",navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"}});const K=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(p.classList.contains("swiper-button-disabled")?p.style.opacity="0.5":p.style.opacity="1")})});K.observe(p,{attributes:!0});const U=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(v.classList.contains("swiper-button-disabled")?v.style.opacity="0.5":v.style.opacity="1")})});U.observe(v,{attributes:!0});const J=new Swiper(".about-me-section .swiper",{breakpoints:{320:{slidesPerView:2},768:{slidesPerView:3},1440:{slidesPerView:6}},loop:!0});document.querySelector(".swiper-button-next-about").addEventListener("click",Q);const d=window.innerWidth;let u=0;d>=320&&d<767&&(u=2);d>=768&&d<1439&&(u=3);d>=1440&&(u=6);function Q(e){const t=document.querySelector(".active-slide-about");if(u>1){console.log(t),t.classList.toggle("active-slide-about"),t.nextElementSibling.classList.toggle("active-slide-about"),u-=1;return}J.slideNext(),t.classList.toggle("active-slide-about"),t.nextElementSibling.classList.toggle("active-slide-about")}//! ============================================
//# sourceMappingURL=commonHelpers.js.map
